import { type NextPage } from "next";
import Head from "next/head";
import React from "react";


const Home: NextPage = (props) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-full justify-center items-center bg-gray-100 " >
        Login to see posts
      </main>
    </>
  );
};

export default Home;
