import { type NextPage } from "next";
import Head from "next/head";
import React from "react";
import { useUser } from "@clerk/nextjs";

const Home: NextPage = () => {
  const { isSignedIn } = useUser();

  if (!isSignedIn) return <div className="h-full justify-center items-center" >Login to see posts</div>

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex w-full h-full justify-center items-center" >
        <div>Here will be landing page</div>
      </main>
    </>
  );
};

export default Home;
