import { type NextPage } from "next";
import Head from "next/head";
import React from "react";
import { useUser } from "@clerk/nextjs";
import Posts from "y/components/post/Posts";


const Home: NextPage = (props) => {
  const { isSignedIn } = useUser();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-full justify-center items-center bg-gray-100 " >
        {isSignedIn ? <Posts /> : <>Login to see posts</>}
      </main>
    </>
  );
};

export default Home;
